POST http://localhost:3000/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "inam@mail.com",
    "password":"12345"
}

### SIGNIN
POST http://localhost:3000/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "ali@mail.com",
    "password":"12345"
}

### Get a user

GET http://localhost:3000/auth/5 HTTP/1.1


